### ISSUE TITLE
Avoid resampling with LADSPA and Pulseaudio

### ISSUE THREAD

**Issue by Ape** [bmc0/dsp#10]
My audio receiver supports multiple sample rates, at least 44.1 kHz and 48 kHz. I also have source material in both of those rates. Pulseaudio supports resampling, but it also can avoid resampling and output the matching sample rate directly when there is only one kind of source playing. Of course, sometimes resampling cannot be avoided, but that is quite rare in my case.

Now, if I have LADSPA dsp enabled it seems to lock the sample rate. Pulseaudio will just always use the default sample rate, even if there is only one source playing and it's just of the other sample rate.

Is it possible to allow Pulseaudio to change the sample rate dynamically with dsp enabled? Dsp should somehow not lock the rate and instead it should operate with the rate that avoids resampling.

**Comment by Ape** [comment]
I did some more research. It seems that the LADSPA output streams are open always, even where there is no input active. I think it would fix this if the LADSPA stream would be closed by default and only opened when some input is active.

**Comment by bmc0** [comment]
Unfortunately, the plugin has no control over that so I can't do anything about pulseaudio's behavior.

The sample rate is set when the `instantiate()` function is called. In order to change the sample rate, the host must call the `cleanup()` function and then call `instantiate()` again with a different sample rate argument. There is also no way for the plugin to close the ports.
