### ISSUE TITLE
speaker management for surround setup

### ISSUE THREAD

**Issue by kalle-del-haye** [bmc0/dsp#11]
I'm trying to use your LADSPA plugin doing the job a AV-receiver does.
But I can't get the bass routing working right.

For a 5.1 setup with full range fronts, a centre playing down to 70 Hz, rears with 120 Hz min and a subwoofer I'm doing:

```
input_channels=6
output_channels=6
LC_NUMERIC=C
#speaker-mapping: 0-left 1-right 2-sl 3-sr 4-center 5-lfe
effects_chain=remix 0 1 2 3 4 5,2,3,4 :2,3 highpass 120 0.5 :4 highpass 70 0.5 :5 lowpass 120 0.5 :
```

But the lowpass for the lfe channel is wrong. I need a different lowpass for center and surrounds an no lowpass for the lfe itself.

So, I'm trying to use multiple remix effects:

```
input_channels=6
output_channels=6
LC_NUMERIC=C
#speaker-mapping: 0-left 1-right 2-sl 3-sr 4-center 5-lfe
effects_chain=remix 0 1 2 3 4 5 :2,3 highpass 120 0.5 :4 highpass 70 0.5 : remix . . . . . 2,3 :5 lowpass 120 0.5 : remix . . . . . 4 :5 lowpass 70 0.5 :
```

But this doesn’t work, I think they are applied in series and not parallel or only the last remix effect is used.

Is it possible to do this kind of bass routing with your plugin?

**Comment by bmc0** [comment]
Let me make sure I understand what you're trying to do... You want to keep the front and LFE channels full range, highpass the center at 70Hz, highpass the rears at 120Hz, and mix lowpassed center (70Hz) and rear (120Hz) signals into the LFE channel?

This will do that:

```
remix 0 1 2 3 4 5 2,3 4 :2,3 highpass 120 0.5 :4 highpass 70 0.5 :6 lowpass 120 0.5 :7 lowpass 70 0.5 : remix 0 1 2 3 4 5,6,7
```

As you said, the effects are applied in series. All you need to do in this case is create two additional channels (one for the mono rear and one for the center), apply the appropriate lowpass filters, and then use another remix effect to mix them back into the LFE channel.

I will warn you that this effects chain may not work quite as intended because the polarity of either the lowpassed or highpassed signals must be inverted (assuming the acoustic centers are aligned) in an LR2 crossover. You can do this by applying `mult -1.0` to the appropriate channels, but you may still have problems for the following reasons:
- If you invert the highpassed signals, it would cause the center channel to be out of phase with the fronts over a very large frequency range. In other words, don't invert the highpassed signals.
- If you invert the lowpassed signals, the center and rear channels will be out of phase with the LFE and front channels at low frequencies. This is much less bad since these channels usually do not all play the same signal, plus the fact that rooms do horrible things to the phase response at low frequencies anyway.
- The center channel will invariably be out of phase with the fronts near the crossover region, which _could_ be a problem since the center and front channels sometimes play very similar signals (take for example a signal panned halfway between the center and right channels).
- Mixing the center and rears into the same channel with different crossover points will cause significant frequency response errors (because of the phase mismatch) if the center and rear signals are very similar (rather unlikely, but something to keep in mind).

I am probably overthinking this, but it may be worth keeping these things in mind.

**Comment by kalle-del-haye** [comment]
First, thanks for your detailed answer.

The possibility of the `remix` effect to create additional 'temporarily' channels is the key. This gives me the flexibility to solve this and other tasks.
Maybe you would add a little hint or an example in the readme - so others will profit from this too.

I'm very new in making crossovers, so I have to learn very much. I'had read a little. A LR 2nd order crossover causes a 180° phase shift. So using a 4th order LR will cause a 360° phase shift and all channels are in the same phase. But the lowpassed parts are one period behind. 
I would use this deffinition for a LR4 filter: `highpass 120 0.7071 highpass 120 0.707`, right?
Don't know if this will be the better solution. Very complex topic to me.

As an alternitive I will trying some linear phase fir filter with your `fir` effect as crossover. So I don't have to care about any phase shifts. It sounds a bit easier to me. And maybe brings a real improvement.

Thank you for your help.

**Comment by bmc0** [comment]
It is true that an LR4 crossover would be "in phase" (delayed one period) at low frequencies, but it will still cause cancellation since the phase will be shifted 180° at the crossover frequency. LR4 probably would be better than LR2 overall because the cancellation would be over a narrower frequency range.

Yes, your LR4 filter is correct.

A linear phase filter is certainly worth trying. Keep in mind that you'll have pre-ringing at the crossover frequency though.
