### ISSUE TITLE
Module will not load in Ubuntu 18.04.

### ISSUE THREAD

**Issue by masterplayer30** [bmc0/dsp#45]
I have done everything in the book and it will still not load at all.

Any fixes to Ubuntu 18.04? Also I need full detailed instructions of how should I make it work.

Bobby Burgess

**Comment by dkucic** [comment]
Run it with pulseaudio --start -vv and provide output from cat /var/log/syslog | grep pulseaudio (immediately after). 
I also had the same issue until I've figured from the logs I need to provide channel number.
Line in my  ~/.config/pulse/default.pa is:

load-module module-ladspa-sink sink_name=dsp sink_master=alsa_output.pci-0000_00_1b.0.analog-stereo plugin=ladspa_dsp label=ladspa_dsp
set-default-sink dsp **channels=2**

Do not just copy & paste the above line since sink_master name needs to be correct.

Could be something entirely different on your system, although pulseaudio feedback and log content should provide some insight. 

BR, Damir

**Comment by masterplayer30** [comment]
I think I got it fixed now. Thank you.
