### ISSUE TITLE
PulseAudio passthrough

### ISSUE THREAD

**Issue by LightBit** [bmc0/dsp#47]
Passthrough in Kodi (with PulseAudio) over S/PDIF stops working (silence), if ladspa_dsp is loaded.
Is there any workaround?

**Comment by bmc0** [comment]
Passthrough unfortunately can't work with `ladspa_dsp` or any other signal processing. With passthrough, codecs like AC3, DTS, and others are passed unmodified to the playback hardware, which is responsible for decoding it (and in some cases, decrypting it as well). If you want to do any kind of signal processing on these codecs you need to decode it to LPCM first.

**Comment by LightBit** [comment]
I understand that, but could it passthrough unmodified without any processing instead of silence?
Problem is S/PDIF does not support multichannel PCM.

**Comment by bmc0** [comment]
Looking at the Kodi documentation, it looks like you can [set the passthrough device separately](https://kodi.wiki/view/Settings/System/Audio#Passthrough_output_device). If you can set it to the actual output device instead of the default device, it should fix your problem.

Trying to detect the format in the LADSPA plugin would be an ugly hack at best. It *could* be done, but I'd really rather not go that route.

**Comment by LightBit** [comment]
It does not help, if I change output device.
This must be some bug in PulseAudio or Kodi.

Thanks anyway.
