### ISSUE TITLE
Locale affects configuration

### ISSUE THREAD

**Issue by LightBit** [bmc0/dsp#60]
Maybe this is expected, but after I changed locale setting to locale with "," instead of "." as decimal point, my config stopped working (ladspa_dsp failed to load).
You can try to set system locale /etc/locale.conf to LC_NUMERIC=sl_SI.UTF-8.

I think it would be better to ignore locale setting to prevent surprises.

**Comment by bmc0** [comment]
It actually does completely ignore locale by default. Because LADSPA plugins are loaded as shared libraries, the default locale is whatever is set by the host program. Issue #5 has some more information.

I recommend adding `LC_NUMERIC=C` to your ladspa_dsp configuration file(s) (as stated in the [README](/bmc0/dsp/blob/master/README.md#configuration)) for predictable behavior. Honestly I should probably make this the default, but I haven't done it yet.
