### ISSUE TITLE
Significant distortion when using eq effect with positive gain

### ISSUE THREAD

**Issue by Ape** [bmc0/dsp#8]
I tried to configure the `eq` effect with LADSPA, but it produces horrible distortion to the sound when the gain is positive. This can be easily reproduced with the following configuration file:

```
effects_chain=eq 106.8 15.0 8.0
```

The distortion only happens when playing close to a specific frequency. I measured that it's loudest at 108.7 Hz.

I didn't hear any distortion with negative gains, but I didn't test it fully yet.

```
dsp f95647b
pulseaudio 7.1
Arch Linux 64 bit
```

**Comment by bmc0** [comment]
This is not a bug. The program does not (and should not) attempt to avoid clipping when you do something like this.

You need to use the `gain` effect to reduce the volume when you use positive gain on a filter:

```
effects_chain=gain -8.0 eq 106.8 15.0 8.0
```

Note that reducing the gain by 8 dB may not completely avoid clipping. A filter like your example will cause complex waveforms to overshoot because it changes the phase response significantly. This is unlikely to be an issue with music, but you may want to reduce the gain by another dB or two just to be safe. You can plot the frequency response of an entire effects chain like this:

```
$ dsp -pn <filters> | gnuplot -p
```

in order to figure out how much to reduce the gain for a more complex effects chain. Note that _some_ effects do not support plotting (`crossfeed`, `remix`,  `delay`, `resample`, etc...).

Filters with negative gains will usually not cause _audible_ clipping, but it is possible for them to clip with waveforms that are not simple sine waves.

**Comment by bmc0** [comment]
Another note: Since `dsp` uses floating point samples internally, you can put the gain effect anywhere because the floating point samples will never clip (unless you go thousands of dB above full scale). You just need to make sure that the final signal that gets converted to integer samples never goes above full scale.

**Comment by richardpl** [comment]
But saving to wav with -e float always clips here

**Comment by bmc0** [comment]
The program clamps each output sample to ±1.0, which is standard for floating point audio. In other words, the samples are not clamped/clipped within the effects chain, but they *are* clipped after it.
